name: Ubuntu
on:
  watch:
    types: started
jobs:
  SSH:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: SSH connection to Actions
      run: |
          pip install -r requirements.txt
          python -m tmate